version: "3.8"
services:
  reports_mongodb:
    image: mongo
    container_name: reports_mongodb
    environment:
      - MONGO_INITDB_DATABASE=reports
      - MONGO_INITDB_ROOT_USERNAME=ivictoriadobos
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
    restart: on-failure
    networks:
      - service_network

  report_service:
    container_name: report_service
    environment:
      - SERVER_PORT=8082
      - MONGODB_URI=mongodb://ivictoriadobos:password@localhost:27017/reports?authSource=admin
      - MONGODB_STATUS_HOST=reports_mongodb
      - MONGODB_STATUS_PORT=27017
    restart: on-failure
    build: .
    ports:
    - 8082:8082
    depends_on:
      - reports_mongodb
    networks:
      - service_network

networks:
  service_network: