version: "3.8"
services:
  orders-database:
    image: mongo
    container_name: reports_mongodb
    environment:
      - MONGO_INITDB_DATABASE=reports
      - MONGO_INITDB_ROOT_USERNAME=ivictoriadobos
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - /home/andrei/ioana/facultate/semestrul 1/PAW/PAW-Report-Service/mongo-volume:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
